channels:
  - conda-forge
dependencies:
  - graphviz
  - ipython
  - metadsl-all
  - pandas
  - python>=3.8
  - python-graphviz
  # dev
  - black
  - docker-compose
  - flake8
  - mypy
  - pip
  - pre-commit
  - pydocstyle
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - jupyter-book>=0.7.0b
  - pip:
    # see .pre-commit-config.yaml, isort pinned
    - seed-isort-config
    # we should try using isort release that will be next after 4.3.21-2
    - git+git://github.com/timothycrosley/isort@18ad293fc9d1852776afe35015a932b68d26fb14#egg=isort
